services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orders'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.12.6-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
